#define CURRENT_SIMTYPE INTERNAL_SIM // replace INTERNAL_SIM with EXTERNAL_SIM --- for external sim
#define CURRENT_SYSTEM_MODE SEMI_AUTOMATIC // replace AUTOMATIC with SEMI_AUTOMATIC --- for external sim
/* #define APN_CREDENTIALS "apn","username","password"    */
/* #define APN_CREDENTIALS "username","password"          --- when only username and password are needed*/
/* #define APN_CREDENTIALS "apn"                          --- when only the apn is needed */
#define APN_CREDENTIALS "safaricom" // for safaricom APN